### ISSUE TITLE
Unhandled rejection TypeError: ... Cannot read property 'substring' of null

### ISSUE THREAD

**Issue by shiaue** [ppoffice/hexo-theme-icarus#106]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [X] I have inited and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [X] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully;
- [x] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

I received the following error- only when I added the "Icarus Theme" to my blog.
Do you have any idea how to fix it?

-

```
Unhandled rejection TypeError: /Users/e/current_projects/blog/themes/icarus/layout/layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

/Users/e/current_projects/blog/themes/icarus/layout/common/head.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%=config.language.substring(0, 2) %>">
    3| <head>
    4|     <meta charset="utf-8">
    5|     <%

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:85)
    at eval (eval at <anonymous> (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:51:978)
    at /Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.ejsRenderer (/Users/e/current_projects/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Render.renderSync (/Users/e/current_projects/blog/node_modules/hexo/lib/hexo/render.js:87:23)
    at View.renderSync (/Users/e/current_projects/blog/node_modules/hexo/lib/theme/view.js:50:29)
    at Object.partial (/Users/e/current_projects/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:19)
    at eval (eval at <anonymous> (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:962)
    at /Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/Users/e/current_projects/blog/node_modules/ejs/lib/ejs.js:293:13)
    at Hexo.ejsRenderer (/Users/e/current_projects/blog/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Hexo.tryCatcher (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Hexo.<anonymous> (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/method.js:15:34)
    at /Users/e/current_projects/blog/node_modules/hexo/lib/hexo/render.js:51:21
    at tryCatcher (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromiseAtPostResolution (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:245:10)
    at Async._drainQueue (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/e/current_projects/blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```
-

My ```hexo version```-

- hexo: 3.1.1
- os: Darwin 14.3.0 darwin x64
- http_parser: 2.6.0
- node: 5.4.1
- v8: 4.6.85.31
- uv: 1.8.0
- zlib: 1.2.8
- ares: 1.10.1-DEV
- icu: 56.1
- modules: 47
- openssl: 1.0.2e

I am running on OS X Yosemite 10.10.3

**Comment by ppoffice** [comment]
You should add the language config to your site's _config.yml file.

https://github.com/ppoffice/hexo-theme-icarus/wiki/FAQ#how-do-i-change-the-sites-language
