### ISSUE TITLE
 Script load failed：index.js

### ISSUE THREAD

**Issue by Skura-Tea** [ppoffice/hexo-theme-icarus#1205]
**Describe the bug**
 Script load failed: themes\icarus\scripts\index.js

**System and Environment**
版本：
hexo: 6.3.0
hexo-cli: 4.3.0
os: win32 10.0.22621
node: 20.2.0
acorn: 8.8.2
ada: 2.4.0
ares: 1.19.0
base64: 0.5.0
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.0
icu: 73.1
llhttp: 8.1.0
modules: 115
napi: 8
nghttp2: 1.52.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.8+quic
simdutf: 3.2.9
tz: 2023c
undici: 5.22.0
unicode: 15.0
uv: 1.44.2
uvwasi: 0.0.16
v8: 11.3.244.8-node.9
zlib: 1.2.13

站点配置除”theme“外与主题配置均为默认

**To Reproduce**

$ hexo s

INFO  Validating config
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
ERROR Script load failed: themes\icarus\scripts\index.js
Error: Cannot find module 'semver'
Require stack:
- D:\blog\themes\icarus\include\dependency.js
- D:\blog\themes\icarus\scripts\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1070:15)
    at Module._load (node:internal/modules/cjs/loader:923:27)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (D:\blog\themes\icarus\include\dependency.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1255:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1137:19)
    at req (D:\blog\node_modules\hexo\lib\hexo\index.js:292:23)
    at D:\blog\themes\icarus\scripts\index.js:19:1
    at D:\blog\node_modules\hexo\lib\hexo\index.js:305:14
    at tryCatcher (D:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blog\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\blog\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\blog\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\blog\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\blog\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\blog\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\blog\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (D:\blog\node_modules\bluebird\js\release\async.js:15:14)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
INFO  Have a nice day

**Additional context**
使用clean清楚缓存依然存在报错，nodejs版本更新至最新同样无法解决

**Comment by ppoffice** [comment]
@Skura-Tea 如果你是从源码安装Icarus的话，也要按照提示安装Icarus的依赖。

参考https://github.com/ppoffice/hexo-theme-icarus/issues/805#issuecomment-718458349

**Comment by Skura-Tea** [comment]
已解决，Thanks

**Comment by weilun0510** [comment]
> 已解决，Thanks

请问怎么解决的
