### ISSUE TITLE
hexo g  error

### ISSUE THREAD

**Issue by captainstdin** [ppoffice/hexo-theme-icarus#1225]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
hexo g的时候报错 ，但是不影响生成
```
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
INFO  Start processing
INFO  Files loaded in 1.03 s
INFO  Deleted: CPRS/index.html
ERROR 
TypeError: Cannot read properties of undefined (reading 'map')
    at _class.render (D:\WebstormProjects\public_blog\node_modules\hexo-theme-icarus\layout\/index.jsx:11:25)
    at renderVNodeToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:210:41)
    at renderVNodeToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:337:37)
    at renderVNodeToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:221:20)
    at renderToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:356:12)
    at D:\WebstormProjects\public_blog\node_modules\hexo-renderer-inferno\lib\compile.js:37:20
    at _View._compiled (D:\WebstormProjects\public_blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\WebstormProjects\public_blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\WebstormProjects\public_blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\WebstormProjects\public_blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\WebstormProjects\public_blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WebstormProjects\public_blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
ERROR
TypeError: Cannot read properties of undefined (reading 'map')
    at _class.render (D:\WebstormProjects\public_blog\node_modules\hexo-theme-icarus\layout\/category.jsx:15:43)
    at renderVNodeToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:210:41)
    at renderToString (D:\WebstormProjects\public_blog\node_modules\inferno-server\dist\index.cjs.js:356:12)
    at D:\WebstormProjects\public_blog\node_modules\hexo-renderer-inferno\lib\compile.js:37:20
    at _View._compiled (D:\WebstormProjects\public_blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\WebstormProjects\public_blog\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\WebstormProjects\public_blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\WebstormProjects\public_blog\node_modules\bluebird\js\release\util.js:16:23)
    at D:\WebstormProjects\public_blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WebstormProjects\public_blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
INFO  Generated: content.json

```

**系统与环境**
 "hexo": {
    "version": "6.3.0"
  },

  "hexo-theme-icarus": "^5.2.1",

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
- 站点配置文件`_config.yml`
- 主题配置文件`_config.icarus.yml`或`themes/icarus/_config.yml`
- 其他额外的配置文件（文章front-matter，`_config.post.yml`，或`_config.page.yml`）
- 浏览器版本（如Firefox 70.0，Chrome Android 80.0）

**复现方式**
hexo g的时候就会出现

**期望行为**
希望他不出现这个错误

**截图**
如果可以的话，请附上几张截图来帮助说明你遇到的问题。

**额外上下文**
我的package.json

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-index-custom": "^1.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-migrator-rss": "^1.1.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-tag-qrcode": "^1.0.0",
    "hexo-theme-icarus": "^5.2.1",
    "hexo-theme-landscape": "^1.0.0"
  }
}

```

**Comment by ppoffice** [comment]
@captainstdin 你的博客里面至少有一篇文章么？另外你有修改Icarus的源代码么？

**Comment by captainstdin** [comment]
有文章的，并且没有修改源码，因为源码在node_modeuls里是锁定的

**Comment by ppoffice** [comment]
`source/tag/index.md`和`source/category/index.md`和`hexo-generator-index`冲突了。其实不用这两个文件也可以显示所有的分类和标签页面的，默认地址是`/categories`和`/tags`。

**Comment by captainstdin** [comment]
You're right ,i have sloved this problem
