### ISSUE TITLE
使用源码安装主题报错

### ISSUE THREAD

**Issue by localhosts-A** [ppoffice/hexo-theme-icarus#1270]
**Bug描述**
使用源码安装主题报错,但是npm安装是可以运行的

**系统与环境**
Windows11 Ubuntu 22.04
Hexo 7.1.1
icarus 5.3.0

- Hexo，操作系统，和Node.js的版本（使用`hexo version`命令来查看）
hexo: 7.1.1
hexo-cli: 4.3.1
os: win32 10.0.22631
node: 20.11.0
acorn: 8.11.2
ada: 2.7.4
ares: 1.20.1
base64: 0.5.1
brotli: 1.0.9
cjs_module_lexer: 1.2.2
cldr: 43.1
icu: 73.2
llhttp: 8.1.1
modules: 115
napi: 9
nghttp2: 1.58.0
nghttp3: 0.7.0
ngtcp2: 0.8.1
openssl: 3.0.12+quic
simdutf: 4.0.4
tz: 2023c
undici: 5.27.2
unicode: 15.0
uv: 1.46.0
uvwasi: 0.0.19
v8: 11.3.244.8-node.17
zlib: 1.2.13.1-motley-5daffc7

**报错信息如下**
ERROR Script load failed: themes\icarus\scripts\index.js
TypeError: require(...) is not a function
    at C:\Users\xxx\Documents\icarus\themes\icarus\scripts\index.js:2:35
    at C:\Users\xxx\Documents\icarus\node_modules\hexo\dist\hexo\index.js:249:20
    at tryCatcher (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\xxx\Documents\icarus\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)

**Comment by localhosts-A** [comment]
似乎在hexo 7.1.1版本上会有这种问题，在hexo6.3.0上面是正常的

**Comment by ppoffice** [comment]
hexo-log 4.0含有不兼容的升级。Fix: b1962d7257c566ea647ac1fd477c5f9df4774ee4
