### ISSUE TITLE
源码使用 6.0.0 异常

### ISSUE THREAD

**Issue by huifer** [ppoffice/hexo-theme-icarus#1283]
环境信息
```
hexo: 7.1.1
hexo-cli: 4.3.1
os: darwin 22.1.0 13.0.1

```

- hexo server 执行内容 

```
ERROR Script load failed: themes/icarus/scripts/index.js
Error: Cannot find module 'semver'
Require stack:
- /Users/zhangsan/hexo/blog/themes/icarus/include/dependency.js
- /Users/zhangsan/hexo/blog/themes/icarus/scripts/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/zhangsan/hexo/blog/themes/icarus/include/dependency.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at req (/Users/zhangsan/hexo/blog/node_modules/hexo/dist/hexo/index.js:241:31)
    at /Users/zhangsan/hexo/blog/themes/icarus/scripts/index.js:21:1
    at /Users/zhangsan/hexo/blog/node_modules/hexo/dist/hexo/index.js:249:20
    at tryCatcher (/Users/zhangsan/hexo/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/zhangsan/hexo/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/zhangsan/hexo/blog/node_modules/bluebird/js/release/promise.js:604:18)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.


```

**Comment by huifer** [comment]
已处理 package.json

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.1.1"
  },
  "dependencies": {
    "bulma-stylus": "0.8.0",
    "hexo": "^7.0.0",
    "hexo-asset-image": "github:CodeFalling/hexo-asset-image",
    "hexo-component-inferno": "^2.0.4",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-pagination": "^3.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-inferno": "^1.0.1",
    "hexo-renderer-multi-markdown-it": "^0.1.5",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-util": "^3.2.0",
    "inferno": "^8.2.3",
    "inferno-create-element": "^8.2.3",
    "semver": "^7.6.0"
  }
}

```
