### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by ilofter** [ppoffice/hexo-theme-icarus#155]
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: /home/iloft/iloft/themes/icarus/layout/index.ejs:2
    1| <% page.posts.each(function(post) { %>                                                                                                                                               
 >> 2|     <%- partial('common/article', { post: post, index: true }) %>                                                                                                                    
    3| <% });                                                                                                                                                                               
    4| if (page.total > 1) { %>                                                                                                                                                             
    5|     <nav id="page-nav">                                                                                                                                                              

/home/iloft/iloft/themes/icarus/layout/common/article.ejs:35                                                                                                                                
    33|         <footer class="article-footer">                                                                                                                                             
    34|             <%- partial('share/index', { post: post }) %>                                                                                                                           
 >> 35|             <%- partial('comment/counter', { post: post }) %>                                                                                                                       
    36|         </footer>                                                                                                                                                                   
    37|     </div>                                                                                                                                                                          
    38|     <% if (!index) { %>                                                                                                                                                             

/home/iloft/iloft/themes/icarus/layout/comment/counter.ejs:2                                                                                                                                
    1| <% if (post.comments) { %>                                                                                                                                                           
 >> 2|     <% if (theme.comment.disqus) { %>
    3|         <a href="<%- post.permalink %>#comments" class="article-comment-link disqus-comment-count" data-disqus-url="<%= post.permalink %>"><%= __('article.comments') %></a>
    4|     <% } else if (theme.comment.duoshuo) { %>
    5|         <a href="<%- post.permalink %>#comments" class="article-comment-link ds-thread-count" data-thread-key="<%= post.permalink %>"><%= __('article.comments') %></a>

Cannot read property 'disqus' of undefined
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1030)
    at ._compiledSync (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:255:15)
    at View.renderSync (/home/iloft/iloft/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/iloft/iloft/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/iloft/iloft/node_modules/lodash/lodash.js:4436:19)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2222)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2621)
    at ._compiledSync (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:255:15)
    at View.renderSync (/home/iloft/iloft/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/iloft/iloft/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/iloft/iloft/node_modules/lodash/lodash.js:4436:19)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:107)
    at Query.forEach (/home/iloft/iloft/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:44)
    at eval (eval at <anonymous> (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:34:72)
    at ._compiledSync (/home/iloft/iloft/node_modules/ejs/lib/ejs.js:255:15)
    at tryCatcher (/home/iloft/iloft/node_modules/bluebird/js/release/util.js:16:23)
    at ._compiled (/home/iloft/iloft/node_modules/bluebird/js/release/method.js:15:34)
    at View.render (/home/iloft/iloft/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/iloft/iloft/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/iloft/iloft/node_modules/bluebird/js/release/util.js:16:23)

**Comment by ppoffice** [comment]
1. 你是照着WiKi中的步骤来安装的么？
2. 请把你的_config.yml贴一下

**Comment by ilofter** [comment]
@ppoffice 尝试更换成了正式版可以正常使用，所有config都没有修改，全新环境只指定了主题

**Comment by wonderomg** [comment]
@ppoffice  icarus主题是直接从https://github.com/ppoffice/hexo-theme-icarus 导下来的，
hexo s就报了题主这样的错

_config.yml内容如下：
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/wonderomg/wonderomg.github.io
  branch: master

**Comment by wonderomg** [comment]
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\projects\git\wonderomg.github.io\themes\icarus\layout\index.ejs:2
    1| <% page.posts.each(function(post) { %>
 >> 2|     <%- partial('common/article', { post: post, index: true }) %>
    3| <% });
    4| if (page.total > 1) { %>
    5|     <nav id="page-nav">

D:\projects\git\wonderomg.github.io\themes\icarus\layout\common\article.ejs:37
    35|         <footer class="article-footer">
    36|             <%- partial('share/index', { post: post }) %>
 >> 37|             <%- partial('comment/counter', { post: post }) %>
    38|         </footer>
    39|     </div>
    40|     <% if (!index) { %>

D:\projects\git\wonderomg.github.io\themes\icarus\layout\comment\counter.ejs:2
    1| <% if (post.comments) { %>
 >> 2|     <% if (theme.comment.disqus) { %>
    3|         <a href="<%- post.permalink %>#comments" class="article-comment-link disqus-comment-count" data-disqus-url="<%= post.permalink %>"><%= __('article.comments') %></a>
    4|     <% } else if (theme.comment.duoshuo) { %>
    5|         <a href="<%- post.permalink %>#comments" class="article-comment-link ds-thread-count" data-thread-key="<%= post.permalink %>"><%= __('article.comments') %></a>

Cannot read property 'disqus' of undefined
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2023)
    at D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\projects\git\wonderomg.github.io\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2485)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2884)
    at D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\projects\git\wonderomg.github.io\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:107)
    at Query.forEach (D:\projects\git\wonderomg.github.io\node_modules\warehouse\lib\query.js:42:5)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:44)
    at eval (eval at <anonymous> (D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:34:72)
    at D:\projects\git\wonderomg.github.io\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\projects\git\wonderomg.github.io\node_modules\hexo\lib\hexo\index.js:390:25

**Comment by wonderomg** [comment]
#13 解决了 my fault 没仔细瞅瞅
