### ISSUE TITLE
 Insight Search error - "no method 'find'"

### ISSUE THREAD

**Issue by RomanBogachev** [ppoffice/hexo-theme-icarus#189]
```bash
# hexo generate
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: Object  has no method 'find'
    at site.posts.sort.filter.filter.map.actualPost (mysite.com/public_html/node_modules/hexo-generator-json-content/index.js:126:20)
    at Query.filter (mysite.com/public_html/node_modules/hexo/node_modules/warehouse/lib/query.js:305:9)
    at Hexo.hexo_generator_json_content (mysite.com/public_html/node_modules/hexo-generator-json-content/index.js:124:7)
    at Hexo.tryCatcher (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at mysite.com/public_html/node_modules/hexo/lib/hexo/index.js:337:24
    at tryCatcher (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:113:31)
    at MappingPromiseArray.init [as _init$] (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/promise_array.js:77:10)
    at MappingPromiseArray._asyncInit (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/map.js:30:10)
    at Async._drainQueue (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (mysite.com/public_html/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)
FATAL Object  has no method 'find'
TypeError: Object  has no method 'find'
```

**Comment by ppoffice** [comment]
@RomanBogachev 
What is your node version? This is a `hexo-generator-json-content` plugin issue.

**Comment by RomanBogachev** [comment]
@ppoffice, 
Version v0.10.46

**Comment by zhishengzhang** [comment]
I have encountered such problems

**Comment by zhishengzhang** [comment]
this is Error Message
![20160926150013](https://cloud.githubusercontent.com/assets/8622157/18825262/12a0c170-83fa-11e6-9b3a-6ea05d954365.png)

**Comment by ppoffice** [comment]
@RomanBogachev @zhishengzhang 

Hello, guys! Sorry for this late reply. I found a function(`Array.prototype.find`) that `hexo-generator-json-content` plugin needs is unavailable in some old versions of Node. Please make sure your Node's version is at least 4.0.0.

Here are some tests:
![qq 20160926153451](https://cloud.githubusercontent.com/assets/8849362/18826201/d2d334d8-83fe-11e6-96a2-3491404af1e5.png)

PS: You can find Node versions and their corresponding V8 engine versions here: https://github.com/hax/hax.github.com/issues/32

**Comment by zhishengzhang** [comment]
@ppoffice  tks.

**Comment by RomanBogachev** [comment]
Now there are no errors, but search doesn`t work.
![2016-10-20 18 46 25](https://cloud.githubusercontent.com/assets/9532289/19567284/c3f2c0be-96f5-11e6-92c9-4bd0dab85682.png)
