### ISSUE TITLE
hexo g style render fail

### ISSUE THREAD

**Issue by c1ay** [ppoffice/hexo-theme-icarus#261]
按照wiki 中install 步骤后，hexo g 报下面的错
```javascript
ERROR Asset render failed: css/style.css
CoercionError: cannot coerce '' to unit
    at Unit.coerce (/home/ubuntu/club/node_modules/stylus/lib/nodes/node.js:248:11)
    at Unit.coerce (/home/ubuntu/club/node_modules/stylus/lib/nodes/unit.js:209:43)
    at Unit.operate (/home/ubuntu/club/node_modules/stylus/lib/nodes/unit.js:132:20)
    at Evaluator.visitBinOp (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:581:28)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitIdent (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:551:22)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitBlock (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.importFile (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:99:18)
    at Evaluator.visitImport (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:920:27)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/ubuntu/club/node_modules/stylus/lib/visitor/evaluator.js:160:18)
```
以下为版本
node v8.0.0
hexo: 3.3.7
hexo-cli: 1.0.3
os: Linux 4.4.0-1013-aws linux x64
http_parser: 2.7.0
node: 8.0.0
v8: 5.8.283.41
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
openssl: 1.0.2k
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b

**Comment by ppoffice** [comment]
@c1ay 我本地升级Hexo到最新版本并没有发现这个问题。请尝试更换低版本node观察是否问题依旧存在。

**Comment by c1ay** [comment]
换成6.10.3 报错如下
```
ERROR Asset render failed: css/style.css
CoercionError: /home/ubuntu/unmannedplane.club/themes/icarus/source/css/_variables.styl:28:54
   24| // Header
   25| header-height = 64px
   26| header-sub-height = 48px
   27| logo-url = hexo-config("customize.logo.url")
   28| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   29| logo-height = 0px + hexo-config("customize.logo.height")
   30|
   31| // Sidebar

cannot coerce '' to unit
```

**Comment by ppoffice** [comment]
@c1ay 请根据_config.yml.example更新下自己的配置文件。

**Comment by c1ay** [comment]
解决了，是我的配置问题，我的 _config.yml 和 theme/icarus/_config.yml 的配置重复了
