### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Billyin1** [ppoffice/hexo-theme-icarus#319]
- [-] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [-] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [-] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

博客风格不能正常显示。

提示如下：

CoercionError: /home/yin/blog/themes/icarus/source/css/_variables.styl:28:54
   24| // Header
   25| header-height = 64px
   26| header-sub-height = 48px
   27| logo-url = hexo-config("customize.logo.url")
   28| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   29| logo-height = 0px + hexo-config("customize.logo.height")
   30| 
   31| // Sidebar

cannot coerce '' to unit

    at Unit.coerce (/home/yin/blog/node_modules/stylus/lib/nodes/node.js:248:11)
    at Unit.coerce (/home/yin/blog/node_modules/stylus/lib/nodes/unit.js:209:43)
    at Unit.operate (/home/yin/blog/node_modules/stylus/lib/nodes/unit.js:132:20)
    at Evaluator.visitBinOp (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:581:28)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitExpression (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:644:26)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitIdent (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:551:22)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitBlock (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:720:39)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.importFile (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:99:18)
    at Evaluator.visitImport (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:920:27)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/home/yin/blog/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.evaluate (/home/yin/blog/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/home/yin/blog/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/home/yin/blog/node_modules/hexo-renderer-stylus/lib/renderer.js:53:6)
    at Hexo.tryCatcher (/home/yin/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/hexo-cli/node_modules/_bluebird@3.5.1@bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/home/yin/blog/node_modules/hexo/lib/hexo/render.js:61:21)

**Comment by Billyin1** [comment]
解决了，抱歉
