### ISSUE TITLE
主题报错,求助！

### ISSUE THREAD

**Issue by shawyo** [ppoffice/hexo-theme-icarus#328]
是这样子的，我在公司的电脑上搭建的`hexo`博客，部署到 `github`上，都没问题,在家的电脑上 `clone` 下来
`npm install` 后 `hexo server`  提示正常，但是在浏览器打开就会终端就会报错；
```
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```
---
hexo 信息
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-content": "^3.0.1",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```
主题版本
```
{
  "name": "hexo-theme-icarus",
  "version": "0.2.1",
  "private": true
}
```
报错信息如下
```
Unhandled rejection TypeError: /Users/shaw/work/hexo/shaw.coding.me/themes/icarus/layout/index.ejs:2
    1| <% page.posts.each(function(post) { %>
 >> 2|     <%- partial('common/article', { post: post, index: true }) %>
    3| <% });
    4| if (page.total > 1) { %>
    5|     <nav id="page-nav">

/Users/shaw/work/hexo/shaw.coding.me/themes/icarus/layout/common/article.ejs:38
    36|         <footer class="article-footer">
    37|             <%- partial('share/index', { post: post }) %>
 >> 38|             <%- partial('comment/counter', { post: post }) %>
    39|         </footer>
    40|     </div>
    41|     <% if (!index) { %>

/Users/shaw/work/hexo/shaw.coding.me/themes/icarus/layout/comment/counter.ejs:2
    1| <% if (post.comments) { %>
 >> 2|     <% if (theme.comment.disqus) { %>
    3|         <a href="<%- post.permalink %>#comments" class="article-comment-link disqus-comment-count" data-disqus-url="<%= post.permalink %>"><%= __('article.comments') %></a>
    4|     <% } else if (theme.comment.duoshuo) { %>
    5|         <a href="<%- post.permalink %>#comments" class="article-comment-link ds-thread-count" data-thread-key="<%= post.permalink %>"><%= __('article.comments') %></a>

Cannot read property 'disqus' of undefined
    at eval (eval at compile (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:12:26)
    at returnedFn (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/shaw/work/hexo/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/shaw/work/hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:92:17)
    at returnedFn (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/shaw/work/hexo/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/shaw/work/hexo/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at compile (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:12:17)
    at Model._Query.Query.Query.forEach (/Users/shaw/work/hexo/node_modules/warehouse/lib/query.js:42:5)
    at eval (eval at compile (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:19)
    at returnedFn (/Users/shaw/work/hexo/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/shaw/work/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/Users/shaw/work/hexo/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/Users/shaw/work/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/shaw/work/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/shaw/work/hexo/node_modules/hexo/lib/hexo/router.js:134:3)
```

**Comment by shawyo** [comment]
`hexo` 是没有问题的，我使用默认的主题`landscape` `hexo`博客是可以正常运行的

**Comment by ppoffice** [comment]
@shawyo 请参照`_config.yml.example`把缺失的配置项补充到`_config.yml`.

**Comment by changchangjie** [comment]
去主题目录下重命名下文件就可以了  Rename _config.yml.example in the theme folder to _config.yml

**Comment by koalahl** [comment]
> 去主题目录下重命名下文件就可以了 Rename _config.yml.example in the theme folder to _config.yml

这个主题pull下来，icarus目录里面是默认没有_config.yml，必须要自己创建一个吗？

**Comment by koalahl** [comment]
我之前用的别的主题， 现在Git pull 下来，主题目录中没有_config.yml文件

**Comment by ppoffice** [comment]
@shawyo #354
