### ISSUE TITLE
执行hexo g出现错误：Asset render failed: css/style.css

### ISSUE THREAD

**Issue by cmlanche** [ppoffice/hexo-theme-icarus#333]
Please make sure these boxes are checked before submitting your issue. Thank you!

- [ ] I have setuped and configurated the blog according to [Hexo official documentation](https://hexo.io/);
- [ ] I have read the [Theme Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki) carefully and created my own configuration file(_config.yml);
- [ ] I have looked up the [Issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no duplicate issues.

请在发布新Issue之前确保你已经进行了如下工作，谢谢！

- [ ] 我已经按照[Hexo官方文档](https://hexo.io/)中的步骤安装与配置了Hexo；
- [ ] 我已经仔细地阅读了[主题Wiki](https://github.com/ppoffice/hexo-theme-icarus/wiki)并创建了自己的配置文件(_config.yml)；
- [ ] 我已经搜索了[Issues](https://github.com/ppoffice/hexo-theme-icarus/issues)，并且没有找到类似的问题。

![](https://tinypng.com/web/output/fju8j5ygx99997wpwna7yw3e3gcuzpqq/QQ20180619-222135%402x.png)

**Comment by Joilence** [comment]
@ppoffice 
遇到同样的问题，不过已发现问题，供参考。

问题大概出在博客目录在 Dropbox 目录下，猜测由于 Dropbox 的即时同步使文件访问出现问题？
虽然没搞清楚其中原理，但在几次实验后在 Dropbox 目录下都会出现问题，而在其他目录不会。

直接 `hexo init` 之后 `hexo g` 会出现问题。

hexo 相关版本信息如下：

```
$ hexo v
hexo: 3.7.1
hexo-cli: 1.1.0
os: Darwin 17.6.0 darwin x64
http_parser: 2.7.0
node: 8.10.0
v8: 6.2.414.50
uv: 1.19.1
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

报错摘要如下：
```
$ hexo g
INFO  Start processing
INFO  Files loaded in 318 ms
ERROR Asset render failed: css/style.css
Error: /Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/themes/landscape/source/css/style.styl:89:29
   85| @import "_partial/highlight"
   86| @import "_partial/mobile"
   87|
   88| if sidebar
   89|   @import "_partial/sidebar"
-----------------------------------^

failed to locate @import file /Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/functions.styl

    at Evaluator.visitImport (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/evaluator.js:915:21)
    at Evaluator.Visitor.visit (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.visitRoot (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/evaluator.js:707:27)
    at Evaluator.Visitor.visit (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/index.js:28:40)
    at Evaluator.visit (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/evaluator.js:160:18)
    at Evaluator.evaluate (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/visitor/evaluator.js:247:15)
    at Renderer.render (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/stylus/lib/renderer.js:86:26)
    at Hexo.module.exports (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/hexo-renderer-stylus/lib/renderer.js:53:6)
    at Hexo.tryCatcher (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.ret (eval at makeNodePromisifiedEval (/Users/jonypro/.nvm/versions/node/v8.10.0/lib/node_modules/hexo/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
    at Promise.then.text (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/hexo/lib/hexo/render.js:61:21)
    at tryCatcher (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/jonypro/Dropbox/[01]Storage/Blogs/joilence.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
```

**Comment by tzxcmer** [comment]
ERROR Asset render failed: css/default.css
Error: /home/tzx/myblog/node_modules/bulma-stylus/stylus/utilities/functions.styl:8:5
    4|     if match('\b(' + $type + ')\b', typeof(v)) != null
    5|       _void = _void + 1;
    6| 
    7|   if length($list) != _void
    8|     error("Unexpected type inside the list.")
----------^
    9|     return false;
   10| 
   11|   return true;

Unexpected type inside the list.

请问一下遇到这个问题怎么解决
