### ISSUE TITLE
ERROR Script load failed: themes/icarus/scripts/index.js

### ISSUE THREAD

**Issue by evawyf** [ppoffice/hexo-theme-icarus#361]
Hi, 
After commonding `hexo s` I meet the issue that 

```
INFO  Checking dependencies
ERROR Script load failed: themes/icarus/scripts/index.js
/Users/Hexo/themes/icarus/includes/specs/config.spec.js:14
    ...require('./meta.spec'),
    ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Hexo/themes/icarus/includes/tasks/check_config.js:8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (/Users/Hexo/node_modules/hexo/lib/hexo/index.js:213:21)
```
Is there miss the './meta.spec'? 

Your design looks great! Hope it will work on my blog soon :D Thanks!

**Comment by ppoffice** [comment]
@evawyf please update your nodes version
