### ISSUE TITLE
Profile页面author_title怎么换行

### ISSUE THREAD

**Issue by wty21cn** [ppoffice/hexo-theme-icarus#37]
请教一下如果希望author_title换行，怎么才能实现，谢谢。

**Comment by ppoffice** [comment]
加\n或者<br />试下

**Comment by wty21cn** [comment]
都不可以  最终生成的页面源代码里面<会变成&lt，\n的话只是代码换了一行并没有加html标签

**Comment by ppoffice** [comment]
试试这样：
author_title: |这是一行
                   这是下一行
注意开始要有`|`

**Comment by GanZhiXiong** [comment]
> 试试这样：
> 
> ```
> author_title: |这是一行
>               这是下一行
> ```
> 
> 注意开始要有`|`

这样写也不行？
大佬还有其他方法吗？

**Comment by GanZhiXiong** [comment]
``` bash
$ hexo s     
INFO  Validating config
FATAL YAMLException: a line break is expected (255:24)

 252 |         # Author title
 253 | #        author_title: Talk is cheap. Show me the code.
 254 | #                     简书、掘金、CSDN将不再更新，所有文章会陆续迁移至该博客。
 255 |         author_title: |这是一行
------------------------------^
 256 |                       这是下一行
 257 |         # Author's current location
    at generateError (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:187:9)
    at readLineBreak (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:391:5)
    at readBlockScalar (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:879:5)
    at composeNode (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1445:35)
    at readBlockMapping (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1441:12)
    at readBlockSequence (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1008:5)
    at composeNode (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1440:12)
    at readBlockMapping (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1164:11)
    at composeNode (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/Users/ganzhixiong/Documents/blog/node_modules/js-yaml/lib/loader.js:1714:19)
    at Hexo.yamlHelper (/Users/ganzhixiong/Documents/blog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/ganzhixiong/Documents/blog/node_modules/hexo/lib/hexo/render.js:75:22
    at tryCatcher (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/ganzhixiong/Documents/blog/node_modules/bluebird/js/release/promise.js:649:10) {
  name: 'YAMLException',
  reason: 'a line break is expected',
```

**Comment by leimao** [comment]
https://github.com/ppoffice/hexo-theme-icarus/discussions/922
