### ISSUE TITLE
如何关闭 donation

### ISSUE THREAD

**Issue by heganyuliang** [ppoffice/hexo-theme-icarus#408]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

donation 部分未作任何设置，在文章末尾就会如此提示：

![报错](https://i.loli.net/2019/02/04/5c57f72620f66.png)

注释掉 donation 部分的代码后，执行 hexo g 时则报错如下：

```
INFO  Checking dependencies
INFO  Validating the configuration file
ERROR Script load failed: themes\icarus\scripts\index.js
YAMLException: bad indentation of a mapping entry at line 77, column 5:
        -
        ^
    at generateError (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at load (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Object.safeLoad (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1591:10)
    at Object.<anonymous> (D:\MEGA\Hexo\themes\icarus\includes\tasks\check_config.js:25:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:227:21)
    at D:\MEGA\Hexo\themes\icarus\scripts\index.js:3:1
    at fs.readFile.then.script (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:240:12)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:614:10)
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
YAMLException: bad indentation of a mapping entry at line 77, column 5:
        -
        ^
    at generateError (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\MEGA\Hexo\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (D:\MEGA\Hexo\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at Promise.then.text (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\render.js:61:21)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\MEGA\Hexo\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\MEGA\Hexo\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\MEGA\Hexo\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\MEGA\Hexo\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\MEGA\Hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
INFO  Files loaded in 832 ms
ERROR D:\MEGA\Hexo\themes\icarus\layout\post.ejs:1
 >> 1| <%- partial('common/article', {post: page, index: false}) %>

D:\MEGA\Hexo\themes\icarus\layout\common\article.ejs:2
    1| <div class="card">
 >> 2|     <% if (has_thumbnail(post)) { %>
    3|     <div class="card-image">
    4|         <%- index ? '<a href="' + url_for(post.link ? post.link : post.path) + '"' : '<span ' %> class="image is-7by1">
    5|             <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
ReferenceError: D:\MEGA\Hexo\themes\icarus\layout\post.ejs:1
 >> 1| <%- partial('common/article', {post: page, index: false}) %>

D:\MEGA\Hexo\themes\icarus\layout\common\article.ejs:2
    1| <div class="card">
 >> 2|     <% if (has_thumbnail(post)) { %>
    3|     <div class="card-image">
    4|         <%- index ? '<a href="' + url_for(post.link ? post.link : post.path) + '"' : '<span ' %> class="image is-7by1">
    5|             <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:11:8)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (D:\MEGA\Hexo\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:11
    9|         <% posts.each(post => { %>
    10|             <article class="media">
 >> 11|                 <% if (has_thumbnail(post)) { %>
    12|                 <a href="<%- url_for((post.link?post.link:post.path)) %>" class="media-left">
    13|                     <p class="image is-64x64">
    14|                         <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
ReferenceError: D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:11
    9|         <% posts.each(post => { %>
    10|             <article class="media">
 >> 11|                 <% if (has_thumbnail(post)) { %>
    12|                 <a href="<%- url_for((post.link?post.link:post.path)) %>" class="media-left">
    13|                     <p class="image is-64x64">
    14|                         <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
    at posts.each.post (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:20:8)
    at Model._Query.Query.Query.forEach (D:\MEGA\Hexo\node_modules\warehouse\lib\query.js:42:5)
    at buildArchive (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:17:14)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:71:17)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:11
    9|         <% posts.each(post => { %>
    10|             <article class="media">
 >> 11|                 <% if (has_thumbnail(post)) { %>
    12|                 <a href="<%- url_for((post.link?post.link:post.path)) %>" class="media-left">
    13|                     <p class="image is-64x64">
    14|                         <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
ReferenceError: D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:11
    9|         <% posts.each(post => { %>
    10|             <article class="media">
 >> 11|                 <% if (has_thumbnail(post)) { %>
    12|                 <a href="<%- url_for((post.link?post.link:post.path)) %>" class="media-left">
    13|                     <p class="image is-64x64">
    14|                         <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
    at posts.each.post (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:20:8)
    at Model._Query.Query.Query.forEach (D:\MEGA\Hexo\node_modules\warehouse\lib\query.js:42:5)
    at buildArchive (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:17:14)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:79:17)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:6
    4|     <div class="card-content">
    5|         <h3 class="tag is-link">
 >> 6|         <%= month === null ? year : time.locale(get_config('language', 'en')).format('MMMM YYYY') %>
    7|         </h3>
    8|         <div class="timeline">
    9|         <% posts.each(post => { %>

get_config is not defined
ReferenceError: D:\MEGA\Hexo\themes\icarus\layout\archive.ejs:6
    4|     <div class="card-content">
    5|         <h3 class="tag is-link">
 >> 6|         <%= month === null ? year : time.locale(get_config('language', 'en')).format('MMMM YYYY') %>
    7|         </h3>
    8|         <div class="timeline">
    9|         <% posts.each(post => { %>

get_config is not defined
    at buildArchive (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:14:55)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:79:17)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR D:\MEGA\Hexo\themes\icarus\layout\index.ejs:2
    1| <% page.posts.each(function(post){ %>
 >> 2|     <%- partial('common/article', { post, index: true }) %>
    3| <% }); %>
    4| <% if (page.total > 1) { %>
    5|     <%- partial('common/paginator') %>

D:\MEGA\Hexo\themes\icarus\layout\common\article.ejs:2
    1| <div class="card">
 >> 2|     <% if (has_thumbnail(post)) { %>
    3|     <div class="card-image">
    4|         <%- index ? '<a href="' + url_for(post.link ? post.link : post.path) + '"' : '<span ' %> class="image is-7by1">
    5|             <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
ReferenceError: D:\MEGA\Hexo\themes\icarus\layout\index.ejs:2
    1| <% page.posts.each(function(post){ %>
 >> 2|     <%- partial('common/article', { post, index: true }) %>
    3| <% }); %>
    4| <% if (page.total > 1) { %>
    5|     <%- partial('common/paginator') %>

D:\MEGA\Hexo\themes\icarus\layout\common\article.ejs:2
    1| <div class="card">
 >> 2|     <% if (has_thumbnail(post)) { %>
    3|     <div class="card-image">
    4|         <%- index ? '<a href="' + url_for(post.link ? post.link : post.path) + '"' : '<span ' %> class="image is-7by1">
    5|             <img class="thumbnail" src="<%= get_thumbnail(post) %>" alt="<%= post.title %>">

has_thumbnail is not defined
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:11:8)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (D:\MEGA\Hexo\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:12:17)
    at Model._Query.Query.Query.forEach (D:\MEGA\Hexo\node_modules\warehouse\lib\query.js:42:5)
    at eval (eval at compile (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:9:19)
    at returnedFn (D:\MEGA\Hexo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\MEGA\Hexo\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (D:\MEGA\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\MEGA\Hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\MEGA\Hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:907:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
INFO  Generated: atom.xml
INFO  Generated: index.html
INFO  Generated: CNAME
INFO  Generated: archives/index.html
INFO  Generated: images/thumbnail.svg
INFO  Generated: images/logo.svg
INFO  Generated: images/avatar.png
INFO  Generated: images/favicon.svg
INFO  Generated: archives/2019/01/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: css/back-to-top.css
INFO  Generated: css/search.css
INFO  Generated: css/progressbar.css
INFO  Generated: js/animation.js
INFO  Generated: js/gallery.js
INFO  Generated: js/clipboard.js
INFO  Generated: css/insight.css
INFO  Generated: js/main.js
INFO  Generated: js/back-to-top.js
INFO  Generated: js/insight.js
INFO  Generated: css/style.css
INFO  Generated: 2019/01/31/hello-world/index.html
INFO  22 files generated in 415 ms
```

请问有无办法直接关掉整个 donation 模块？

**Comment by ppoffice** [comment]
@heganyuliang 直接把`donate`部分删掉或者写成`donate:false`

**Comment by heganyuliang** [comment]
解决了，感谢！
