### ISSUE TITLE
有错误代码

### ISSUE THREAD

**Issue by LiYanan2004** [ppoffice/hexo-theme-icarus#412]
ERROR Script load failed: themes\icarus\scripts\index.js
D:\Hexo\hexo\themes\icarus\includes\specs\config.spec.js:14
    ...require('./meta.spec'),
    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Hexo\hexo\themes\icarus\includes\tasks\check_config.js:8:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (D:\Hexo\hexo\node_modules\hexo\lib\hexo\index.js:213:21)
    at D:\Hexo\hexo\themes\icarus\scripts\index.js:3:1
    at D:\Hexo\hexo\node_modules\hexo\lib\hexo\index.js:229:12
    at tryCatcher (D:\Hexo\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Hexo\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Hexo\hexo\node_modules\bluebird\js\release\promise.js:569:18)

**Comment by ppoffice** [comment]
@请升级nodejs

**Comment by LiYanan2004** [comment]
解决了谢谢
