### ISSUE TITLE
安装后使用hexo s无法启动

### ISSUE THREAD

**Issue by yzx9607** [ppoffice/hexo-theme-icarus#423]
安装后使用hexo s无法启动

**Comment by ppoffice** [comment]
@yzx9607 请附上错误提示与console的输出

**Comment by xanderma** [comment]
INFO  Checking dependencies
ERROR Script load failed: themes\icarus\scripts\index.js
I:\MyProject\blog\blog\themes\icarus\includes\specs\config.spec.js:14
    ...require('./meta.spec'),
    ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (I:\MyProject\blog\blog\themes\icarus\includes\tasks\check_config.js:8:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (I:\MyProject\blog\blog\node_modules\hexo\lib\hexo\index.js:227:21)
    at I:\MyProject\blog\blog\themes\icarus\scripts\index.js:3:1
    at fs.readFile.then.script (I:\MyProject\blog\blog\node_modules\hexo\lib\hexo\index.js:240:12)
    at tryCatcher (I:\MyProject\blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:614:10)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

**Comment by xanderma** [comment]
> INFO Checking dependencies
> ERROR Script load failed: themes\icarus\scripts\index.js
> I:\MyProject\blog\blog\themes\icarus\includes\specs\config.spec.js:14
> ...require('./meta.spec'),
> ^^^
> SyntaxError: Unexpected token ...
> at Object.exports.runInThisContext (vm.js:78:16)
> at Module._compile (module.js:543:28)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:488:32)
> at tryModuleLoad (module.js:447:12)
> at Function.Module._load (module.js:439:3)
> at Module.require (module.js:498:17)
> at require (internal/module.js:20:19)
> at Object. (I:\MyProject\blog\blog\themes\icarus\includes\tasks\check_config.js:8:18)
> at Module._compile (module.js:571:32)
> at Object.Module._extensions..js (module.js:580:10)
> at Module.load (module.js:488:32)
> at tryModuleLoad (module.js:447:12)
> at Function.Module._load (module.js:439:3)
> at Module.require (module.js:498:17)
> at require (I:\MyProject\blog\blog\node_modules\hexo\lib\hexo\index.js:227:21)
> at I:\MyProject\blog\blog\themes\icarus\scripts\index.js:3:1
> at fs.readFile.then.script (I:\MyProject\blog\blog\node_modules\hexo\lib\hexo\index.js:240:12)
> at tryCatcher (I:\MyProject\blog\blog\node_modules\bluebird\js\release\util.js:16:23)
> at Promise._settlePromiseFromHandler (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:512:31)
> at Promise._settlePromise (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:569:18)
> at Promise._settlePromise0 (I:\MyProject\blog\blog\node_modules\bluebird\js\release\promise.js:614:10)
> INFO Start processing
> INFO Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

升级nodejs版本后解决了

**Comment by koliy** [comment]
非常感谢。。愁死我了。原来是node版本低的问题。
