### ISSUE TITLE
categories 生成失败

### ISSUE THREAD

**Issue by jingzhouzhao** [ppoffice/hexo-theme-icarus#521]
Cannot read property 'forEach' of undefined                                          at eval (eval at exports.compile (D:\zhaojingzhou\io\hexo\node_modules\ejs\l ib\ejs.js:242:14), :30:338)                                               at eval (eval at exports.compile (D:\zhaojingzhou\io\hexo\node_modules\ejs\l ib\ejs.js:242:14), :30:799)                                               at D:\zhaojingzhou\io\hexo\node_modules\ejs\lib\ejs.js:255:15                    at Theme._View.View._compiled (D:\zhaojingzhou\io\hexo\node_modules\hexo\lib \theme\view.js:127:30)                                                               at Theme._View.View.View.render (D:\zhaojingzhou\io\hexo\node_modules\hexo\l ib\theme\view.js:29:15)                                                              at D:\zhaojingzhou\io\hexo\node_modules\hexo\lib\hexo\index.js:387:25            at tryCatcher (D:\zhaojingzhou\io\hexo\node_modules\bluebird\js\release\util .js:16:23)                                                                           at D:\zhaojingzhou\io\hexo\node_modules\bluebird\js\release\method.js:15:34      at RouteStream._read (D:\zhaojingzhou\io\hexo\node_modules\hexo\lib\hexo\rou ter.js:134:3)                                                                        at RouteStream.Readable.read (_stream_readable.js:443:10)                        at resume_ (_stream_readable.js:823:12)                                          at _combinedTickCallback (internal/process/next_tick.js:138:11)                  at process._tickCallback (internal/process/next_tick.js:180:9)               Unhandled rejection TypeError: D:\zhaojingzhou\io\hexo\themes\icarus\layout\cate gory.ejs:6                                                                           4\|                                                                           5\|             <%= _p('common.ca tegory', Infinity) %>                                                    >> 6\|             <% page.parents.forEach(category => { %>                          7\|             <%= category.name  %>                                                                         8\|             <% }) %>                                                          9\|             <%= pag e.category %>                                                                                                                                            Cannot read property 'forEach' of undefined                                          at eval (eval at exports.compile (D:\zhaojingzhou\io\hexo\node_modules\ejs\l ib\ejs.js:242:14), :30:338)                                               at eval (eval at exports.compile (D:\zhaojingzhou\io\hexo\node_modules\ejs\l ib\ejs.js:242:14), :30:799)                                               at D:\zhaojingzhou\io\hexo\node_modules\ejs\lib\ejs.js:255:15                    at Theme._View.View._compiled (D:\zhaojingzhou\io\hexo\node_modules\hexo\lib \theme\view.js:127:30)                                                               at Theme._View.View.View.render (D:\zhaojingzhou\io\hexo\node_modules\hexo\l ib\theme\view.js:29:15)                                                              at D:\zhaojingzhou\io\hexo\node_modules\hexo\lib\hexo\index.js:387:25            at tryCatcher (D:\zhaojingzhou\io\hexo\node_modules\bluebird\js\release\util .js:16:23)                                                                           at D:\zhaojingzhou\io\hexo\node_modules\bluebird\js\release\method.js:15:34      at RouteStream._read (D:\zhaojingzhou\io\hexo\node_modules\hexo\lib\hexo\rou ter.js:134:3)                                                                        at RouteStream.Readable.read (_stream_readable.js:443:10)                        at resume_ (_stream_readable.js:823:12)                                          at _combinedTickCallback (internal/process/next_tick.js:138:11)                  at process._tickCallback (internal/process/next_tick.js:180:9)
--

**Comment by jingzhouzhao** [comment]
是我的问题，对比了你们的site分支的package.json后发现我的hexo的版本是3.2的，升级为3.9就没有问题了。
