### ISSUE TITLE
使用hexo-neat时返回顶部无法使用

### ISSUE THREAD

**Issue by FFRaycoder** [ppoffice/hexo-theme-icarus#608]
报错：
```
ERROR Asset render failed: js/back-to-top.js
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at expect_token (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2110:9)
    at expect (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2113:36)
    at regular_for (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2354:9)
    at for_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2350:16)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2229:24)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2407:15)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2232:24)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2401:25)
    at function_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2407:15)
    at expr_atom (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2622:24)
    at maybe_unary (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2792:19)
    at expr_ops (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2827:24)
    at maybe_conditional (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2832:20)
ERROR Asset render failed: js/main.js
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103:9)
    at semicolon (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2123:56)
    at simple_statement (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2314:73)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2183:19)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2190:29)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at if_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2412:44)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2235:24)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2190:29)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at if_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2412:44)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2235:24)
    at eval (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2136:24)
    at block_ (eval at <anonymous> (D:\workspace\hexo\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2429:20)
```

**Comment by ppoffice** [comment]
@DoraMrKim Please report this to hexo-neat.

**Comment by moegay** [comment]
@DoraMrKim 
在hexo的config里把报错的俩js（back-to-top.js和main.js）加入neat_js的exclude列表即可。写法如下：

neat_enable: true
neat_js:
  enable: true
  exclude:
    - '**/back-to-top.js'
    - '**/main.js'
