### ISSUE TITLE
The theme can't load

### ISSUE THREAD

**Issue by zhangferry** [ppoffice/hexo-theme-icarus#636]
Please make sure you took care of the following things before you submit this issue. Thank you!

- [ * ] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [ * ] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

My previous site worked well, then a change site theme to icarus and run `hexo clean`. I got the `_config.yml`, then I do nothing only run `hexo g`, those bug log appear:
```
TypeError: /Users/zhangferry/zhangferry.github.io/themes/icarus/layout/page.ejs:1
 >> 1| <%- _partial('common/article', {post: page, index: false}) %>

/Users/zhangferry/zhangferry.github.io/themes/icarus/layout/common/article.ejs:56
    54|                 <div class="level-item">
    55|                     <span class="is-size-6 has-text-grey has-mr-7">#</span>
 >> 56|                     <%- list_tags(post.tags, {
    57|                         class: 'has-link-grey ',
    58|                         show_count: false,
    59|                         style: 'link'

tags.sort is not a function
    at Object.listTagsHelper (/Users/zhangferry/zhangferry.github.io/node_modules/hexo/lib/plugins/helper/list_tags.js:24:15)
    at eval (eval at compile (/Users/zhangferry/zhangferry.github.io/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:105:17)
    at returnedFn (/Users/zhangferry/zhangferry.github.io/node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/zhangferry/zhangferry.github.io/node_modules/hexo/lib/theme/view.js:121:22)
    at Theme._View.View.View.renderSync (/Users/zhangferry/zhangferry.github.io/node_modules/hexo/lib/theme/view.js:49:23)
    at Object.partial (/Users/zhangferry/zhangferry.github.io/node_modules/hexo/lib/plugins/helper/partial.js:38:15)
    at Object.<anonymous> (/Users/zhangferry/zhangferry.github.io/themes/icarus/includes/helpers/override.js:190:42)
    at eval (eval at compile (/Users/zhangferry/zhangferry.github.io/node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:17)
    at returnedFn (/Users/zhangferry/zhangferry.github.io/node_modules/ejs/lib/ejs.js:653:17)
```

**Comment by ppoffice** [comment]
@zhangferry What's your hexo version?

**Comment by zhangferry** [comment]
@ppoffice 
```
hexo: 3.8.0
hexo-cli: 3.1.0
os: Darwin 19.0.0 darwin x64
node: 11.6.0
v8: 7.0.276.38-node.13
uv: 1.24.1
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
```

**Comment by ppoffice** [comment]
@zhangferry Please upgrade your Hexo and its dependencies.
https://github.com/ppoffice/hexo-theme-icarus/blob/site/package.json#L6

**Comment by zhangferry** [comment]
@ppoffice I did think it was a release problem, but when I upgraded the hexo version and its dependencies, I still got the bug. so sad.
hexo version:
```
hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 19.0.0 darwin x64
node: 11.6.0
v8: 7.0.276.38-node.13
uv: 1.24.1
zlib: 1.2.11
ares: 1.15.0
modules: 67
nghttp2: 1.34.0
napi: 3
llhttp: 1.0.1
http_parser: 2.8.0
openssl: 1.1.0j
icu: 63.1
unicode: 11.0
cldr: 34.0
tz: 2018e
```
package.json:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "cheerio": "^1.0.0-rc.3",
    "hexo": "^4.2.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-searchdb": "^1.2.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-symbols-count-time": "^0.7.0"
  }
}
```

**Comment by ppoffice** [comment]
@zhangferry Could you also do `hexo clean`?

**Comment by zhangferry** [comment]
@ppoffice Yes, I did, but it didn't help

**Comment by zhangferry** [comment]
@ppoffice Despite those error log, I was able to preview through `hexo s` and the preview seemed to find. Will it make any difference?

**Comment by ppoffice** [comment]
@zhangferry Perhaps one of your post is not correctly configured. Please find which post it is from the error log and post the markdown here.

**Comment by zhangferry** [comment]
@ppoffice Thanks you so much! The problom solved. 
I had found tag format error on the md file in about folder. After the fix, the problem was solved.
