### ISSUE TITLE
Error encountered during generating.

### ISSUE THREAD

**Issue by boxlab** [ppoffice/hexo-theme-icarus#643]
The following error was encountered while generating

```
ERROR G:\Blog\themes\hexo-theme-icarus\layout\tag.ejs:11
    9|     </div>
    10| </div>
 >> 11| <%- _partial('index', { page }) %>

G:\Blog\themes\hexo-theme-icarus\layout\index.ejs:1
 >> 1| <% page.posts.each(function(post){ %>
    2|     <%- _partial('common/article', { post, index: true }) %>
    3| <% }); %>
    4| <% if (page.total > 1) { %>

Cannot read property 'each' of undefined
TypeError: G:\Blog\themes\hexo-theme-icarus\layout\tag.ejs:11
    9|     </div>
    10| </div>
 >> 11| <%- _partial('index', { page }) %>

G:\Blog\themes\hexo-theme-icarus\layout\index.ejs:1
 >> 1| <% page.posts.each(function(post){ %>
    2|     <%- _partial('common/article', { post, index: true }) %>
    3| <% }); %>
    4| <% if (page.total > 1) { %>

Cannot read property 'each' of undefined
    at eval (eval at compile (G:\Blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:9:19)
    at returnedFn (G:\Blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (G:\Blog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (G:\Blog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (G:\Blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at Object.<anonymous> (G:\Blog\themes\hexo-theme-icarus\includes\helpers\override.js:171:20)
    at eval (eval at compile (G:\Blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:19:17)
    at returnedFn (G:\Blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (G:\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at G:\Blog\node_modules\hexo\lib\hexo\index.js:349:21
    at tryCatcher (G:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\Blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
ERROR G:\Blog\themes\hexo-theme-icarus\layout\category.ejs:6
    4|         <ul>
    5|             <li><a href="<%- url_for('/categories') %>"><%= _p('common.category', Infinity) %></a></li>
 >> 6|             <% page.parents.forEach(category => { %>
    7|             <li><a href="<%- url_for(category.path) %>"><%= category.name %></a></li>
    8|             <% }) %>
    9|             <li class="is-active"><a href="#" aria-current="page"><%= page.category %></a></li>

Cannot read property 'forEach' of undefined
TypeError: G:\Blog\themes\hexo-theme-icarus\layout\category.ejs:6
    4|         <ul>
    5|             <li><a href="<%- url_for('/categories') %>"><%= _p('common.category', Infinity) %></a></li>
 >> 6|             <% page.parents.forEach(category => { %>
    7|             <li><a href="<%- url_for(category.path) %>"><%= category.name %></a></li>
    8|             <% }) %>
    9|             <li class="is-active"><a href="#" aria-current="page"><%= page.category %></a></li>

Cannot read property 'forEach' of undefined
    at eval (eval at compile (G:\Blog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:16:21)
    at returnedFn (G:\Blog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (G:\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (G:\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at G:\Blog\node_modules\hexo\lib\hexo\index.js:349:21
    at tryCatcher (G:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\Blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\Blog\node_modules\hexo\lib\hexo\router.js:123:3)
    at RouteStream.Readable.read (_stream_readable.js:453:10)
    at resume_ (_stream_readable.js:929:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

- [x] I have set up and configured my blog according to the [Hexo docs](https://hexo.io/) and the [Icarus docs](https://ppoffice.github.io/hexo-theme-icarus/);
- [x] I have looked up [Github issues](https://github.com/ppoffice/hexo-theme-icarus/issues) and found no solutions to my problems.

**Comment by boxlab** [comment]
I found the reason. I have a new custom category and tags page before.

**Comment by khanhtc1202** [comment]
@boxlab could you share your solution for this, I get some similar errors when I run generate blog content.

**Comment by boxlab** [comment]
> @boxlab could you share your solution for this, I get some similar errors when I run generate blog content.

@khanhtc1202 The category page and tags page I created previously conflict with the theme page. Just delete them
