### ISSUE TITLE
Error: Cannot find module 'hexo/lib/models/post'

### ISSUE THREAD

**Issue by keithWSY** [ppoffice/hexo-theme-icarus#675]
大佬，我今天安装碰到了这个问题，使用hexo自带的主题没有问题，使用icarus就报错了
尝试： npm install post --save 过，没有效果
报错信息如下：
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
INFO  === Registering Hexo extensions ===
ERROR Script load failed: themes/icarus/scripts/index.js
Error: Cannot find module 'hexo/lib/models/post'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at module.exports.hexo (/Users/keithwang/node_modules/_hexo-component-inferno@0.2.3@hexo-component-inferno/lib/hexo/filter/locals.js:33:23)
    at module.exports.hexo (/Users/keithwang/dom/biubiubiu/blog/themes/icarus/include/register.js:5:61)
    at /Users/keithwang/dom/biubiubiu/blog/themes/icarus/scripts/index.js:29:31
    at readFile.then.script (/Users/keithwang/dom/biubiubiu/blog/node_modules/hexo/lib/hexo/index.js:293:14)
    at tryCatcher (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/promise.js:673:18)
    at /Users/keithwang/dom/biubiubiu/blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/keithwang/dom/biubiubiu/blog/node_modules/graceful-fs/graceful-fs.js:115:16

我的版本信息：
hexo-cli: 3.1.0
os: Darwin 17.4.0 darwin x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e

**Comment by ppoffice** [comment]
@keithWSY 
https://hexo.io/zh-cn/docs/setup

![InkedScreenshot_2020-04-13 建站_LI](https://user-images.githubusercontent.com/8849362/79157224-38d6da00-7da2-11ea-954c-e0299a466802.jpg)

**Comment by keithWSY** [comment]
现在 部署 和启动都没有问题了，但是打开界面报错 
sh-3.2# hexo g
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
INFO  === Registering Hexo extensions ===
INFO  Start processing
INFO  Files loaded in 179 ms
INFO  Generated: content.json
INFO  Generated: index.html
INFO  Generated: js/algolia.js
INFO  Generated: js/google_cse.js
INFO  Generated: js/insight.js
INFO  Generated: categories/index.html
INFO  Generated: archives/index.html
INFO  Generated: tags/index.html
INFO  Generated: img/avatar.png
INFO  Generated: js/main.js
INFO  Generated: js/animation.js
INFO  Generated: js/back_to_top.js
INFO  Generated: img/logo.svg
INFO  Generated: img/razor-bottom-black.svg
INFO  Generated: img/razor-top-black.svg
INFO  Generated: img/og_image.png
INFO  Generated: img/favicon.svg
INFO  Generated: img/thumbnail.svg
INFO  Generated: archives/2020/04/index.html
INFO  Generated: archives/2020/index.html
INFO  Generated: css/cyberpunk.css
INFO  Generated: css/default.css
INFO  Generated: css/style.css
INFO  Generated: 2020/04/13/hello-world/index.html
INFO  24 files generated in 2.09 s
sh-3.2# hexo s
INFO  =======================================
 ██╗ ██████╗ █████╗ ██████╗ ██╗   ██╗███████╗
 ██║██╔════╝██╔══██╗██╔══██╗██║   ██║██╔════╝
 ██║██║     ███████║██████╔╝██║   ██║███████╗
 ██║██║     ██╔══██║██╔══██╗██║   ██║╚════██║
 ██║╚██████╗██║  ██║██║  ██║╚██████╔╝███████║
 ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝
=============================================
INFO  === Checking package dependencies ===
INFO  === Checking the configuration file ===
INFO  === Registering Hexo extensions ===
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.

打http://localhost:4000/ 报错 
const { Component } = require('inferno'); const classname = require('hexo-component-inferno/lib/util/classname'); const Head = require('./common/head'); const Navbar = require('./common/navbar'); const Widgets = require('./common/widgets'); const Footer = require('./common/footer'); const Scripts = require('./common/scripts'); const Search = require('./common/search'); module.exports = class extends Component { render() { const { env, site, config, page, helper, body } = this.props; const language = page.lang || page.language || config.language; const columnCount = Widgets.getColumnCount(config.widgets); return
; } };

**Comment by ppoffice** [comment]
@keithWSY 请提供确保Icarus的所有依赖正确安装，并且在此Issue中提供正确的错误提示

**Comment by keithWSY** [comment]
大佬， 不好意思，问题没有描述清楚，目前是 hexo g 和 hexo s 是成功的，没有错误信息；
但是访问 http://localhost:4000/ 显示如下信息 
不清楚是缺了什么依赖？hexo g和s是i成功的 
![image](https://user-images.githubusercontent.com/25559566/79195171-65512b80-7e60-11ea-80d7-43e4cbbc9fab.png)

**Comment by ppoffice** [comment]
把你博客的源代码上传一下吧，要不然这点信息也没法debug
