### ISSUE TITLE
hexo generate

### ISSUE THREAD

**Issue by mohamed0group** [ppoffice/hexo-theme-icarus#695]
```
ERROR Cannot read property 'each' of undefined
TypeError: Cannot read property 'each' of undefined
    at _class.render (/Volumes/mac d/just cooking/justcooking/themes/icarus/layout/archive.jsx:41:24)
    at renderVNodeToString (/Volumes/mac d/just cooking/justcooking/node_modules/inferno-server/dist/index.cjs.js:206:41)
    at renderToString (/Volumes/mac d/just cooking/justcooking/node_modules/inferno-server/dist/index.cjs.js:352:12)
    at /Volumes/mac d/just cooking/justcooking/node_modules/hexo-renderer-inferno/lib/compile.js:37:20
    at viewFn._compiled (/Volumes/mac d/just cooking/justcooking/node_modules/hexo/lib/theme/view.js:136:48)
    at viewFn.View.render (/Volumes/mac d/just cooking/justcooking/node_modules/hexo/lib/theme/view.js:41:15)
    at /Volumes/mac d/just cooking/justcooking/node_modules/hexo/lib/hexo/index.js:61:21
    at tryCatcher (/Volumes/mac d/just cooking/justcooking/node_modules/bluebird/js/release/util.js:16:23)
    at /Volumes/mac d/just cooking/justcooking/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Volumes/mac d/just cooking/justcooking/node_modules/hexo/lib/hexo/router.js:126:3)
    at RouteStream.Readable.read (_stream_readable.js:478:10)
    at resume_ (_stream_readable.js:965:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ppoffice** [comment]
I need more context. Please update your issue following the issue template.

**Comment by mohamed0group** [comment]
@ppoffice  thanks i fix the issue by reseting yamil file. but i still have issue when i deploy to netlify server.
