### ISSUE TITLE
hexo g 安装报错

### ISSUE THREAD

**Issue by PhenixZhang** [ppoffice/hexo-theme-icarus#814]
> 确保你在提交Bug反馈之前仔细阅读了[Hexo文档](https://hexo.io/zh-cn/)，[Icarus用户指南](https://ppoffice.github.io/hexo-theme-icarus/tags/Icarus%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/)，和[GitHub issues](https://github.com/ppoffice/hexo-theme-icarus/issues)来了解你的问题是否已经被他人提出过。

**Bug描述**
安装报错
  err: OperationalError: /Users/zhangyunfei06/zhangyunfei06/hexo/themes/next/source/css/main.styl:14:11
     10| // --------------------------------------------------
     11| for $variable in $variables
     12|   @import "_variables/" + $variable;
     13| for $inject_variable in hexo-config('injects.variable')
     14|   @import $inject_variable;
  -----------------^
     15|
     16| // Mixins Layer
     17| // --------------------------------------------------

  @import string expected

      at Evaluator.visitImport (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:887:27)
      at Evaluator.Visitor.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
      at Evaluator.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:160:18)
      at Evaluator.visitBlock (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:720:39)
      at Evaluator.Visitor.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
      at Evaluator.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:160:18)
      at visitBody (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:433:17)
      at Evaluator.visitEach (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:449:7)
      at Evaluator.Visitor.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
      at Evaluator.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:160:18)
      at Evaluator.visitRoot (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:707:27)
      at Evaluator.Visitor.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/index.js:28:40)
      at Evaluator.visit (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:160:18)
      at Evaluator.evaluate (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/visitor/evaluator.js:247:15)
      at Renderer.render (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/stylus/lib/renderer.js:86:26)
      at Hexo.stylusFn (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/hexo-renderer-stylus/lib/renderer.js:59:6)
      at Hexo.tryCatcher (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Hexo.ret (eval at makeNodePromisifiedEval (/Users/zhangyunfei06/.nvm/versions/node/v15.3.0/lib/node_modules/hexo/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:39)
      at /Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/hexo/lib/hexo/render.js:75:22
      at tryCatcher (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/zhangyunfei06/zhangyunfei06/hexo/node_modules/bluebird/js/release/promise.js:604:18) {
    cause: Error: /Users/zhangyunfei06/zhangyunfei06/hexo/themes/next/source/css/main.styl:14:11

**系统与环境**
列出你的Hexo和Icarus的版本和配置。
INFO  === Checking package dependencies ===
INFO  === Checking theme configurations ===
INFO  === Registering Hexo extensions ===
hexo: 5.2.0
hexo-cli: 4.2.0
os: Darwin 19.6.0 darwin x64
node: 15.3.0
v8: 8.6.395.17-node.22
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 88
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0

- 浏览器版本（Chrome Android 80.0）

**复现方式**
按照安装

1. 访问‘...’
2. 点击’...‘
3. 下拉到‘...’
4. 出现‘...’的错误

**期望行为**
期望能够解决bug
**截图**
如果可以的话，请附上几张截图来帮助说明你遇到的问题。

**额外上下文**
附上与问题有关的其他上下文信息。

**Comment by ppoffice** [comment]
@PhenixZhang `err: OperationalError: /Users/zhangyunfei06/zhangyunfei06/hexo/themes/next/source/css/main.styl:14:11`

你这儿出错的是themes/next。你确定你用的是icarus主题？
